products:
  path: /bilemo/products
  controller: App\Controller\ProductsController::ShowProducts

singleproducts:
  path: /bilemo/products/{id}
  controller: App\Controller\ProductsController::ShowSingleProducts


adduser:
  path: /bilemo/users/{clientsid}/adduser
  controller: App\Controller\UsersController::AddUser


deleteuser:
  path: /bilemo/users/{clientsid}/deluser/{usersid}
  controller: App\Controller\UsersController::DeleteUser

users:
  path: /bilemo/users/{clientsid}
  controller: App\Controller\UsersController::ShowUsers

singleuser:
  path: /bilemo/users/{clientsid}/{usersid}
  controller: App\Controller\UsersController::ShowSingleUsers



#index:
#    path: /
#    controller: App\Controller\DefaultController::index
