api_login_check:
  path: /bilemo/login

products:
  path: /bilemo/products
  controller: App\Controller\ProductsController::ShowProducts

singleproducts:
  path: /bilemo/products/{id}
  controller: App\Controller\ProductsController::ShowSingleProducts

users:
  path: /bilemo/users
  controller: App\Controller\UsersController::Users

singleuser:
  path: /bilemo/users/{usersid}
  controller: App\Controller\UsersController::SingleUser



#index:
#    path: /
#    controller: App\Controller\DefaultController::index
