products:
  path: /bilemo/products
  controller: App\Controller\ProductsController::ShowProducts
  methods: GET

singleproducts:
  path: /bilemo/products/{id}
  controller: App\Controller\ProductsController::ShowSingleProducts
  methods: GET

addclient:
  path: /bilemo/clients/{usersid}/addclient/
  controller: App\Controller\ClientsController::AddClient

addclientvalide:
  path: /bilemo/clients/{usersid}/addclientvalide
  controller: App\Controller\ClientsController::AddClientValide
  requirements:
    _method: POST

deleteclient:
  path: /bilemo/clients/{usersid}/delclient/{clientsid}
  controller: App\Controller\ClientsController::DeleteClient

clients:
  path: /bilemo/clients/{usersid}
  controller: App\Controller\ClientsController::ShowClients
  methods: GET

singleclients:
  path: /bilemo/clients/{usersid}/{clientsid}
  controller: App\Controller\ClientsController::ShowSingleClients
  methods: GET


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
