products:
  path: /bilemo/products
  controller: App\Controller\ProductsController::ShowProducts

singleproducts:
  path: /bilemo/products/{id}
  controller: App\Controller\ProductsController::ShowSingleProducts


addclient:
  path: /bilemo/clients/{usersid}/addclient
  controller: App\Controller\ClientsController::AddClient


deleteclient:
  path: /bilemo/clients/{usersid}/delclient/{clientsid}
  controller: App\Controller\ClientsController::DeleteClient

clients:
  path: /bilemo/clients/{usersid}
  controller: App\Controller\ClientsController::ShowClients

singleclients:
  path: /bilemo/clients/{usersid}/{clientsid}
  controller: App\Controller\ClientsController::ShowSingleClients



#index:
#    path: /
#    controller: App\Controller\DefaultController::index
