app.swagger:
    path: /bilemo/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /bilemo/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login_check:
  path: /bilemo/login
  controller: App\Controller\UsersController::login
  methods:    POST

products:
  path: /bilemo/products
  controller: App\Controller\ProductsController::ShowProducts
  methods:    GET

singleproducts:
  path: /bilemo/products/{id}
  controller: App\Controller\ProductsController::ShowSingleProducts
  methods:    GET

usersshow:
  path: /bilemo/users
  controller: App\Controller\UsersController::UsersShow
  methods:    GET

usersadd:
  path: /bilemo/users
  controller: App\Controller\UsersController::UsersAdd
  methods:    POST

singleusershow:
  path: /bilemo/users/{usersid}
  controller: App\Controller\UsersController::SingleUserShow
  methods:    GET

singleuserdelete:
  path: /bilemo/users/{usersid}
  controller: App\Controller\UsersController::SingleUserDelete
  methods:    DELETE




#index:
#    path: /
#    controller: App\Controller\DefaultController::index
